### ISSUE TITLE
NS_ERROR_UNEXPECTED on firefox.

### ISSUE THREAD

**Issue by karan-t** [tinymce/tinymce-svelte#42]
Hi,

I currently have 2 components where component 1 has a TinyMCE Editor. Clicking on a button mounts component 2. When component 2 mounts I face this error "NS_ERROR_UNEXPECTED" only on firefox. This occurs randomly and the only change in the DOM I see is the node with class "tox tox-silver-sink tox-tinymce-aux" remains when this error occurs. When I don't face the error, I can't find this. Sorry if this is a basic issue that I'm failing to solve.

**Comment by cornzz** [comment]
Hi, we also had this issue and found a fix:
For us it occured when programatically changing the `value` prop of `<Editor>`, which we bind, and then unmounting the component which contained the editor. It would throw the error only if the editor content was not changed by keyboard input afterwards. The fix was to reload the editor component by wrapping it in a key block:

```
let reloadCounter = 0
const reloadEditor = () => reloadCounter++

...

{#key reloadCounter}
    <Editor ... />
{/key}
```
