### ISSUE TITLE
Support for Svelte

### ISSUE THREAD

**Issue by Mrbeyond** [tinymce/tinymce-svelte#5]
Request for svelte framework support out of box.

**Comment by jscasca** [comment]
@EugeneGoroschenyaExt the thing is that `lastVal` is just an auxiliary variable and not the actual value of the editor. In line 106 you'll see that it is actually set before it is used.

https://github.com/tinymce/tinymce-svelte/blob/f4755575de764e6c377602f65edfc2cdcf07bc06/src/main/component/Editor.svelte#L106-L110

So `value` doesn't need to change since it is the value set by the user before setting it into the editor

**Comment by jscasca** [comment]
Okay, I see your point. Yeah, that makes sense now. I'll try to get this done by the weekend. Thanks for bringing it up!
