### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by murtyjones** [tinymce/tinymce-svelte#8]
Is there a way to pass class names to the editor, or more specifically to specify height (e.g. "100%")?

**Comment by jscasca** [comment]
@murtyjones you can use the TinyMCE `height` configuration property to set to `100%` however it currently is limited by a div wrapping the editor inside the component. You can either style this div or after #9 has been merged you will be able to name the wrapper so that you can find it easily to set the height you need (`100vh` for example or whatever works for you)
E.G: if you have the following conf:
```
<script>
let conf = { height: '100%'}
let css = 'my-wrapper';
</script>
```
You can either:
```
<style>
    .my-wrapper > div { height: 100vh;}
  </style>
<div class="my-wrapper">
    <Editor {conf} />
  </div>
```
Or:
```
<style>
    .my-wrapper { height: 100vh;}
  </style>
<div>
    <Editor cssClass={css} {conf} />
  </div>
```
